### ISSUE TITLE
Интеграция перестала работать после обновления блоков 

### ISSUE THREAD

**Issue by Ot4eVash** [and7ey/haier_evo#22]
15.10 два блока AS25S2SF2FA обновились через EVO на 1.4.8. Сама EVO тоже обновилась.
Интеграция перестала работать.

![EVO](https://github.com/user-attachments/assets/3867400a-355b-4d59-b773-b5845b5c543b)

**Comment by JampireX** [comment]
hsu_07hrm203_r3_in
> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/__init__.py", line 24, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/api.py", line 144, in pull_data
    if len(devices) > 0:
           ^^^^^^^
UnboundLocalError: cannot access local variable 'devices' where it is not associated with a value

**Comment by JampireX** [comment]
https://github.com/and7ey/haier_evo/blob/a9c43e40b6bbb943e283d0141f6da11dcb29cca0/custom_components/haier_evo/api.py#L144

**Comment by JampireX** [comment]
Сейчас интеграция заработала. Судя по всему временные проблемы на сервере API могли быть.

**Comment by Ot4eVash** [comment]
Подтверждаю. Всё заработало!

**Comment by Ot4eVash** [comment]
Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.

**Comment by JampireX** [comment]
> Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.

Тоже обратил внимание на это. Немного покопал - интеграция в какой-то момент пытаясь авторизоваться получает от сервера 429 ошибку (too many requests). Как столкнусь еще раз - приложу подробную ошибку из лога.

Возможно раньше сервер позволял чаще проводить авторизацию, а теперь лимит был снижен.

При этом родное приложение не отваливается, предполагаю оно гораздо реже обновляет токен и не лезет на сервер так часто как пытается это делать интеграция.

**Comment by Ot4eVash** [comment]
> > Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.
> 
> Тоже обратил внимание на это. Немного покопал - интеграция в какой-то момент пытаясь авторизоваться получает от сервера 429 ошибку (too many requests). Как столкнусь еще раз - приложу подробную ошибку из лога.
> 
> Возможно раньше сервер позволял чаще проводить авторизацию, а теперь лимит был снижен.
> 
> При этом родное приложение не отваливается, предполагаю оно гораздо реже обновляет токен и не лезет на сервер так часто как пытается это делать интеграция.

Подтверждаю ошибку 429. Кстати, умный дом яндекса тоже не отваливается. Но он тоже очень редко обновляет токен.

**Comment by JampireX** [comment]
> > > Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.
> > 
> > 
> > Тоже обратил внимание на это. Немного покопал - интеграция в какой-то момент пытаясь авторизоваться получает от сервера 429 ошибку (too many requests). Как столкнусь еще раз - приложу подробную ошибку из лога.
> > Возможно раньше сервер позволял чаще проводить авторизацию, а теперь лимит был снижен.
> > При этом родное приложение не отваливается, предполагаю оно гораздо реже обновляет токен и не лезет на сервер так часто как пытается это делать интеграция.
> 
> Подтверждаю ошибку 429. Кстати, умный дом яндекса тоже не отваливается. Но он тоже очень редко обновляет токен.

Судя по тому что я вижу в коде интеграции - она вполне себе нормально смотрит на срок истечения токена. Подозреваю дело в том, что мы в альтернативу интеграции начали использовать родное приложение и ему ведь тоже токен обновлять приходится - таким образом с одной сети двумя источниками мы и превышаем количество допустимых запросов и одно из приложений отваливается.

**Comment by Ot4eVash** [comment]
> > > > Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.
> > > 
> > > 
> > > Тоже обратил внимание на это. Немного покопал - интеграция в какой-то момент пытаясь авторизоваться получает от сервера 429 ошибку (too many requests). Как столкнусь еще раз - приложу подробную ошибку из лога.
> > > Возможно раньше сервер позволял чаще проводить авторизацию, а теперь лимит был снижен.
> > > При этом родное приложение не отваливается, предполагаю оно гораздо реже обновляет токен и не лезет на сервер так часто как пытается это делать интеграция.
> > 
> > 
> > Подтверждаю ошибку 429. Кстати, умный дом яндекса тоже не отваливается. Но он тоже очень редко обновляет токен.
> 
> Судя по тому что я вижу в коде интеграции - она вполне себе нормально смотрит на срок истечения токена. Подозреваю дело в том, что мы в альтернативу интеграции начали использовать родное приложение и ему ведь тоже токен обновлять приходится - таким образом с одной сети двумя источниками мы и превышаем количество допустимых запросов и одно из приложений отваливается.

Увы, но интеграция имеет очень ограниченный функционал и без родного приложения не обойтись.

**Comment by JampireX** [comment]
> > > > > Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.
> > > > 
> > > > 
> > > > Тоже обратил внимание на это. Немного покопал - интеграция в какой-то момент пытаясь авторизоваться получает от сервера 429 ошибку (too many requests). Как столкнусь еще раз - приложу подробную ошибку из лога.
> > > > Возможно раньше сервер позволял чаще проводить авторизацию, а теперь лимит был снижен.
> > > > При этом родное приложение не отваливается, предполагаю оно гораздо реже обновляет токен и не лезет на сервер так часто как пытается это делать интеграция.
> > > 
> > > 
> > > Подтверждаю ошибку 429. Кстати, умный дом яндекса тоже не отваливается. Но он тоже очень редко обновляет токен.
> > 
> > 
> > Судя по тому что я вижу в коде интеграции - она вполне себе нормально смотрит на срок истечения токена. Подозреваю дело в том, что мы в альтернативу интеграции начали использовать родное приложение и ему ведь тоже токен обновлять приходится - таким образом с одной сети двумя источниками мы и превышаем количество допустимых запросов и одно из приложений отваливается.
> 
> Увы, но интеграция имеет очень ограниченный функционал и без родного приложения не обойтись.

С этим согласен. В интеграции отсутствуют режимы турбо и тишины в моем случае. Но похоже проблема в данном контексте не решаемая, если только не реализовать возможность интеграции ходить через прокси, тем самым иметь отдельную квоту запросов к серверу.

**Comment by Ot4eVash** [comment]
> > > > > > Возобновляю проблему! Интеграция отваливается на 12 часов каждый день.
> > > > > 
> > > > > 
> > > > > Тоже обратил внимание на это. Немного покопал - интеграция в какой-то момент пытаясь авторизоваться получает от сервера 429 ошибку (too many requests). Как столкнусь еще раз - приложу подробную ошибку из лога.
> > > > > Возможно раньше сервер позволял чаще проводить авторизацию, а теперь лимит был снижен.
> > > > > При этом родное приложение не отваливается, предполагаю оно гораздо реже обновляет токен и не лезет на сервер так часто как пытается это делать интеграция.
> > > > 
> > > > 
> > > > Подтверждаю ошибку 429. Кстати, умный дом яндекса тоже не отваливается. Но он тоже очень редко обновляет токен.
> > > 
> > > 
> > > Судя по тому что я вижу в коде интеграции - она вполне себе нормально смотрит на срок истечения токена. Подозреваю дело в том, что мы в альтернативу интеграции начали использовать родное приложение и ему ведь тоже токен обновлять приходится - таким образом с одной сети двумя источниками мы и превышаем количество допустимых запросов и одно из приложений отваливается.
> > 
> > 
> > Увы, но интеграция имеет очень ограниченный функционал и без родного приложения не обойтись.
> 
> С этим согласен. В интеграции отсутствуют режимы турбо и тишины в моем случае. Но похоже проблема в данном контексте не решаемая, если только не реализовать возможность интеграции ходить через прокси, тем самым иметь отдельную квоту запросов к серверу.

Не знаю, на сколько правдиво и актуально, но наткнулся на такую статью:
https://www.linux.org.ru/news/opensource/17493319

Если так, то политика Haier - "Сами не сделаем и вам не дадим"

**Comment by TohaRG2** [comment]
Регулярно отваливается при перезагрузке, если с момента последней перезагрузки интеграции прошло меньше недели. Соответственно по 429 ошибке (слишком частые обновления). 

2024-12-02 22:56:52.453 DEBUG (MainThread) [custom_components.haier_evo] Integration version: 0.3.0
2024-12-02 22:56:52.454 DEBUG (SyncWorker_16) [custom_components.haier_evo.api] Refresh token expired or empty
2024-12-02 22:56:52.455 DEBUG (SyncWorker_16) [custom_components.haier_evo.api] Logging in to https://evo.haieronline.ru/v1/users/auth/sign-in with email avхххххх@yandex.ru
2024-12-02 22:56:52.560 DEBUG (SyncWorker_16) [custom_components.haier_evo.api] Login (avхххххх@yandex.ru) status code: 429
2024-12-02 22:56:52.560 ERROR (SyncWorker_16) [custom_components.haier_evo.api] Failed to login/refresh token for email avхххххх@yandex.ru, response was: <Response [429]>
2024-12-02 22:56:52.561 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry avхххххх@yandex.ru for haier_evo

**Comment by and7ey** [comment]
> Не знаю, на сколько правдиво и актуально, но наткнулся на такую статью: https://www.linux.org.ru/news/opensource/17493319
> 
> Если так, то политика Haier - "Сами не сделаем и вам не дадим"

Это правда, но это про другую интеграцию (если ваш кондиционер работает через приложение hOn - то это ваш случай). Для российского рынка сделали другое приложение - evo -  и с его создателями пока таких проблем не было.

Попробуйте новую версию интеграции, в нем попробовали решить проблему с ошибкой 429.

**Comment by Ot4eVash** [comment]
> > Не знаю, на сколько правдиво и актуально, но наткнулся на такую статью: https://www.linux.org.ru/news/opensource/17493319
> > Если так, то политика Haier - "Сами не сделаем и вам не дадим"
> 
> Это правда, но это про другую интеграцию (если ваш кондиционер работает через приложение hOn - то это ваш случай). Для российского рынка сделали другое приложение - evo - и с его создателями пока таких проблем не было.
> 
> Попробуйте новую версию интеграции, в нем попробовали решить проблему с ошибкой 429.

Спасибо за ответ и что не забрасываете интеграцию! Но давно уже перешёл на локальную интеграцию через ESPHome и забыл все эти проблемы.
