### ISSUE TITLE
Не подключается интеграция status code: 429

### ISSUE THREAD

**Issue by TohaRG2** [and7ey/haier_evo#24]
Отваливается подключение, выдает "не удалось настроить"

2024-10-24 11:12:17.252 DEBUG (MainThread) [custom_components.haier_evo] Integration version: 0.3.0
2024-10-24 11:12:17.254 DEBUG (SyncWorker_33) [custom_components.haier_evo.api] Refresh token expired or empty
2024-10-24 11:12:17.254 DEBUG (SyncWorker_33) [custom_components.haier_evo.api] Logging in to https://evo.haieronline.ru/v1/users/auth/sign-in with email хххххххх@yandex.ru
2024-10-24 11:12:17.349 DEBUG (SyncWorker_33) [custom_components.haier_evo.api] Login (хххххххх@yandex.ru) status code: 429
2024-10-24 11:12:17.350 ERROR (SyncWorker_33) [custom_components.haier_evo.api] Failed to login/refresh token for email хххххххх@yandex.ru, response was: <Response [429]>
2024-10-24 11:12:17.351 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry хххххххх@yandex.ru for haier_evo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/__init__.py", line 24, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/api.py", line 104, in pull_data
    self.auth()
  File "/config/custom_components/haier_evo/api.py", line 100, in auth
    self.login()
  File "/config/custom_components/haier_evo/api.py", line 85, in login
    raise InvalidAuth()
custom_components.haier_evo.api.InvalidAuth

**Comment by TohaRG2** [comment]
Само заработало.
