### ISSUE TITLE
Перестала загружаться инеграция

### ISSUE THREAD

**Issue by dkras** [and7ey/haier_evo#25]
Перестала загружаться интеграция
В логах ошибка:

This error originated from a custom integration.

Logger: custom_components.haier_evo.api
Source: custom_components/haier_evo/api.py:82
integration: Haier Evo (documentation, issues)
First occurred: 8:27:28 AM (2 occurrences)
Last logged: 8:28:43 AM

Failed to login/refresh token for email xxxx@gmail.ru, response was: <Response [429]>

**Comment by DrRamm** [comment]
Ага, вчера впервые добавил её. А сегодня утром уже отвалилась


```
2024-11-03 12:43:19.101 ERROR (SyncWorker_14) [custom_components.haier_evo.api] Failed to login/refresh token for email XXXXXXXXXXX@icloud.com, response was: <Response [429]>
2024-11-03 12:43:19.102 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry XXXXXXXXXXX@icloud.com for haier_evo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/__init__.py", line 24, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/api.py", line 104, in pull_data
    self.auth()
  File "/config/custom_components/haier_evo/api.py", line 100, in auth
    self.login()
  File "/config/custom_components/haier_evo/api.py", line 85, in login
    raise InvalidAuth()
custom_components.haier_evo.api.InvalidAuth
```

**Comment by DrRamm** [comment]
Ну мало ли 
https://github.com/and7ey/haier_evo/pull/26

**Comment by AirAlarm** [comment]
> Ну мало ли 
> 
> https://github.com/and7ey/haier_evo/pull/26

Такая же ошибка, думал, что пароль неправильно ввожу.) 
Можно как-то самому временно починить?

**Comment by and7ey** [comment]
попробуйте новую версию
