### ISSUE TITLE
Периодически отваливается управление кондиционером

### ISSUE THREAD

**Issue by TohaRG2** [and7ey/haier_evo#5]
Периодически отваливается управление кондиционером, при попытке вызвать любое действие - ssl.SSLError: [SSL: BAD_LENGTH] bad length. Помогает только перезагрузка учетной записи. Лог 
[home-assistant_haier_evo_2024-06-08T15-26-52.454Z.log](https://github.com/user-attachments/files/15748632/home-assistant_haier_evo_2024-06-08T15-26-52.454Z.log)

**Comment by Stillezzen** [comment]
После обновления НА до версии 2024.6.1, перезагрузка не помогает.

**Comment by TohaRG2** [comment]
Причем отваливается только AS25HPL1HRA, второй кондей AS25HPL2HRA пока вроде не отваливался. Но AS25HPL1HRA - после обновления данных работает буквально несколько минут и отваливается. Причем то выдает
"Этот объект больше не предоставляется интеграцией haier_evo. Вы можете удалить его на вкладке "Настройки", если он больше не будет использоваться"
то пишет, что кондиционер выключен (хотя он в этот момент может быть и включен) и как и писал выше - SSL: BAD_LENGTH при попытке выполнить любое действие.

**Comment by Stillezzen** [comment]
У меня после отвала ошибка при попытке изменить температуру «Не удалось вызвать службу climate/set_temperature. EOF occurred in violation of protocol (_ssl.c:2406)»

**Comment by 1vanchik** [comment]
Также получаю ошибку 

2024-06-11 11:14:33.913 DEBUG (SyncWorker_40) [custom_components.haier_evo.api] Sending message for command switchOn: {"action": "operation", "macAddress": "a0:a3:b3:b6:9c:70", "commandName": "3", "commands": [{"commandName": "21", "value": "1"}, {"commandName": "5", "value": "0"}]}
2024-06-11 11:14:33.914 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140733704999200] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 808, in async_turn_on
    await self.hass.async_add_executor_job(self.turn_on)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/haier_evo/climate.py", line 67, in turn_on
    self._module.switchOn()
  File "/config/custom_components/haier_evo/api.py", line 448, in switchOn
    self._send_message(json.dumps(
  File "/config/custom_components/haier_evo/api.py", line 383, in _send_message
    self._socket_app.send(payload)
  File "/usr/local/lib/python3.12/site-packages/websocket/_app.py", line 290, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 297, in send
    return self.send_frame(frame)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 337, in send_frame
    l = self._send(data)
        ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_core.py", line 559, in _send
    return send(self.sock, data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 179, in send
    return _send()
           ^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/websocket/_socket.py", line 156, in _send
    return sock.send(data)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/ssl.py", line 1180, in send
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2406)


После перезагрузки интеграции всё работает

**Comment by 1vanchik** [comment]
Есть какие-то успехи на этот счёт?

**Comment by TohaRG2** [comment]
После какого-то сбоя (отвалились оба кондея в EVO), и переподключения их в EVO. В HA один успешно подключается AS25HPL2HRA, а второй AS25HPL1HRA находится, добавляется, но при попытке управления говорит, что "Этот объект больше не предоставляется интеграцией haier_evo." 
[home-assistant_haier_evo_2024-06-19T14-44-49.074Z.log](https://github.com/user-attachments/files/15902603/home-assistant_haier_evo_2024-06-19T14-44-49.074Z.log)

**Comment by and7ey** [comment]
@1vanchik  @TohaRG2  @Stillezzen Повторяется ли проблема с версией 0.3.0?

**Comment by TohaRG2** [comment]
Все ОК, теперь другая проблема заведу новый issue

**Comment by Stillezzen** [comment]
> @1vanchik @TohaRG2 @Stillezzen Повторяется ли проблема с версией 0.3.0?

Я ушёл на haier-esphome

**Comment by TohaRG2** [comment]
Ну т.е. если я правильно понял, то для этого надо перепрошить usb-стик в кондее или сделать новый. В целом не выглядит большой проблемой, но управление будет только из HomeAssistant? Я в основном кондеем через сбер-колонку управляю, в HA скорее резервный вариант для управления, ну и отброс состояния на планшет у входа, чтобы можно было включить/выключить из прихожей легким нажатием.

**Comment by Stillezzen** [comment]
@TohaRG2 новый есп. Родные зашифрованы. По управлению всё решаемо. Правда у меня Яндекс станция.

**Comment by TohaRG2** [comment]
@Stillezzen Понятно. В принципе как раз новый ESP32 недавно пришел с алика, надо будет попробовать (главное время найти). Спасибо за идею.
